/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import entidades.Polera;
import entidades.Pantalon;
import entidades.Gorro;
import entidades.Vestidor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author USER
 */
public class ListaDeRopa extends javax.swing.JFrame {

    private List<Gorro> gorros = new ArrayList<>();
    private List<Polera> poleras = new ArrayList<>();
    private List<Pantalon> pantalones = new ArrayList<>();
    private List<Vestidor> vestidores = new ArrayList<>();
    DefaultListModel modeloLista = new DefaultListModel();

    /**
     * Creates new form ListaDeRopa
     */
    public ListaDeRopa() {
        initComponents();
        lstPrendas.setModel(modeloLista);
    }

    //Métodos
    private void buscar() {
        modeloLista.removeAllElements();
        for (Vestidor ves : vestidores) {
            if (ves.getNombre().toLowerCase()
                    .contains(txtBuscar.getText().toLowerCase())) {
                modeloLista.addElement(ves.getNombre());
            }
        }
    }

    public void actualizarLista() {
        modeloLista.removeAllElements();
        for (Vestidor nav : vestidores) {
            modeloLista.addElement(nav.getNombre());
        }
    }

    public void setPantalon(Pantalon pantalon) {
        pantalones.add(pantalon);
        vestidores.add(pantalon);
        actualizarLista();
    }

    public void setPolera(Polera polera) {
        poleras.add(polera);
        vestidores.add(polera);
        actualizarLista();
    }

    public void setGorro(Gorro gorro) {
        gorros.add(gorro);
        vestidores.add(gorro);
        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnGorros = new javax.swing.JButton();
        btnPantalones = new javax.swing.JButton();
        btnPoleras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPrendas = new javax.swing.JList<>();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Ropa");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Ingrese prenda a registrar");

        btnBuscar.setBackground(new java.awt.Color(255, 255, 153));
        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGorros.setBackground(new java.awt.Color(255, 153, 153));
        btnGorros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGorros.setText("Agregar Gorros");
        btnGorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGorrosActionPerformed(evt);
            }
        });

        btnPantalones.setBackground(new java.awt.Color(255, 153, 153));
        btnPantalones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPantalones.setText("Agregar Pantalones");
        btnPantalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPantalonesActionPerformed(evt);
            }
        });

        btnPoleras.setBackground(new java.awt.Color(255, 153, 153));
        btnPoleras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPoleras.setText("Agregar Poleras");
        btnPoleras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolerasActionPerformed(evt);
            }
        });

        lstPrendas.setBackground(new java.awt.Color(204, 255, 255));
        lstPrendas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstPrendas);

        txtBuscar.setBackground(new java.awt.Color(204, 255, 255));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(202, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnGorros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPoleras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPantalones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnBuscar)))
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPantalones)
                        .addGap(18, 18, 18)
                        .addComponent(btnPoleras)
                        .addGap(18, 18, 18)
                        .addComponent(btnGorros)))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        modeloLista.removeAllElements();
        for (Vestidor nav : vestidores) {
            if (nav.getNombre() == txtBuscar.getText()) {
                modeloLista.addElement(nav.getNombre());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPantalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPantalonesActionPerformed
        EditarPantalon agregarPantalon = new EditarPantalon(this);
        agregarPantalon.setLocationRelativeTo(null);
        agregarPantalon.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPantalonesActionPerformed

    private void btnPolerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolerasActionPerformed
        EditarPolera agregarPolera = new EditarPolera(this);
        agregarPolera.setLocationRelativeTo(null);
        agregarPolera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPolerasActionPerformed

    private void btnGorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGorrosActionPerformed
        EditarGorro agregarPolo = new EditarGorro(this);
        agregarPolo.setLocationRelativeTo(null);
        agregarPolo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGorrosActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDeRopa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGorros;
    private javax.swing.JButton btnPantalones;
    private javax.swing.JButton btnPoleras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPrendas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
